// TaxDesk filing lifecycle — single source of truth.
// Stages: created → documents_requested → documents_received → in_preparation
//         → client_review → filed → completed. Overdue is a flag, not a stage:
// if due_date passes before `filed`, the filing shows Overdue (red) + notifies.

export const FILING_STAGES = [
  { key: "created", label: "Created", clientLabel: "Received", actor: "system", desc: "Made manually or auto-generated by a tax rule template (e.g. monthly VAT)." },
  { key: "documents_requested", label: "Documents requested", clientLabel: "Upload documents", actor: "client", desc: "Client is notified to upload what's needed; shows as an upload action item." },
  { key: "documents_received", label: "Documents received", clientLabel: "Documents received", actor: "accountant", desc: "Accountant reviews uploads live." },
  { key: "in_preparation", label: "In preparation", clientLabel: "Being prepared", actor: "accountant", desc: "Return prepared; amount owed / refund calculated." },
  { key: "client_review", label: "Client review & e-sign", clientLabel: "Review & sign", actor: "client", desc: "Client approves and signs; timestamped signature record stored." },
  { key: "filed", label: "Filed", clientLabel: "Filed", actor: "accountant", desc: "Submitted; filed_at recorded; fee invoice generated." },
  { key: "completed", label: "Completed", clientLabel: "Completed", actor: "system", desc: "Payment received; receipt available for download." },
] as const;

export type FilingStageKey = (typeof FILING_STAGES)[number]["key"] | "overdue";

// Legacy aliases from v1 → canonical stage (backwards compatible with old rows)
const LEGACY_MAP: Record<string, string> = {
  pending: "created",
  in_progress: "in_preparation",
  in_review: "client_review",
  filed: "filed",
  completed: "completed",
  overdue: "overdue",
  todo: "created",
  done: "completed",
};

export function normalizeStage(status: string | null | undefined): string {
  const s = String(status ?? "created").toLowerCase().trim().replace(/ /g, "_");
  if (FILING_STAGES.some((st) => st.key === s)) return s;
  return LEGACY_MAP[s] ?? "created";
}

export function stageIndex(status: string | null | undefined): number {
  const n = normalizeStage(status);
  if (n === "overdue") return -1; // overdue overlays whatever stage it was in
  return FILING_STAGES.findIndex((s) => s.key === n);
}

export function stageLabel(status: string | null | undefined, forClient = false): string {
  const n = normalizeStage(status);
  if (n === "overdue") return "Overdue";
  const st = FILING_STAGES.find((s) => s.key === n);
  if (!st) return String(status);
  return forClient ? st.clientLabel : st.label;
}

export function nextStage(status: string | null | undefined): string | null {
  const i = stageIndex(status);
  if (i < 0 || i >= FILING_STAGES.length - 1) return null;
  return FILING_STAGES[i + 1].key;
}

export function isTerminal(status: string | null | undefined): boolean {
  const n = normalizeStage(status);
  return n === "filed" || n === "completed";
}

export function isComplete(status: string | null | undefined): boolean {
  return normalizeStage(status) === "completed";
}

export function isFiledOrLater(status: string | null | undefined): boolean {
  const n = normalizeStage(status);
  return n === "filed" || n === "completed";
}

/** Overdue = due date passed AND not yet filed/completed. Red on dashboards. */
export function isOverdue(status: string, dueDate: string | null | undefined): boolean {
  if (!dueDate) return normalizeStage(status) === "overdue";
  if (isFiledOrLater(status)) return false;
  if (normalizeStage(status) === "overdue") return true;
  return new Date(dueDate).getTime() < Date.now();
}

/** Effective display status: "overdue" flag wins over stage when past due. */
export function displayStatus(status: string, dueDate: string | null | undefined): string {
  return isOverdue(status, dueDate) ? "overdue" : normalizeStage(status);
}

/** Who acts next at this stage (for action-item generation). */
export function stageActor(status: string | null | undefined): string {
  const n = normalizeStage(status);
  const st = FILING_STAGES.find((s) => s.key === n);
  return st?.actor ?? "accountant";
}

/** Client action item for the current stage, if any. */
export function clientActionFor(status: string | null | undefined): string | null {
  const n = normalizeStage(status);
  if (n === "documents_requested") return "upload documents";
  if (n === "client_review") return "review and sign";
  if (n === "filed") return "pay invoice";
  return null;
}

// Role permissions (mirrored by Supabase RLS in supabase/migrations/*)
export function canAdvance(role: "admin" | "employee" | "client", status: string | null | undefined): boolean {
  const n = normalizeStage(status);
  if (role === "client") return n === "client_review" || n === "documents_requested"; // upload + sign
  return true; // admin + assigned employee move filings through stages
}

export const CLIENT_STEPPER = ["Received", "Upload documents", "Being prepared", "Review & sign", "Filed", "Completed"];
export function clientStepperIndex(status: string | null | undefined): number {
  const map: Record<string, number> = {
    created: 0, documents_requested: 1, documents_received: 2, in_preparation: 2,
    client_review: 3, filed: 4, completed: 5,
  };
  return map[normalizeStage(status)] ?? 0;
}
